//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ISO20022.Auth_061_001_02 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02", IsNullable=false)]
    public partial class Document {
        
        private CCPInvestmentsReportV02 cCPInvstmtsRptField;
        
        /// <remarks/>
        public CCPInvestmentsReportV02 CCPInvstmtsRpt {
            get {
                return this.cCPInvstmtsRptField;
            }
            set {
                this.cCPInvstmtsRptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class CCPInvestmentsReportV02 {
        
        private Investment2Choice[] invstmtField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Invstmt")]
        public Investment2Choice[] Invstmt {
            get {
                return this.invstmtField;
            }
            set {
                this.invstmtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class Investment2Choice {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CntrlBkDpst", typeof(Deposit1))]
        [System.Xml.Serialization.XmlElementAttribute("OthrInvstmts", typeof(OtherInvestment1))]
        [System.Xml.Serialization.XmlElementAttribute("OutrghtInvstmt", typeof(SecurityIdentificationAndAmount2))]
        [System.Xml.Serialization.XmlElementAttribute("RpAgrmt", typeof(RepurchaseAgreement2))]
        [System.Xml.Serialization.XmlElementAttribute("UscrdCshDpst", typeof(Deposit1))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class Deposit1 {
        
        private System.DateTime mtrtyDtField;
        
        private ActiveCurrencyAndAmount valField;
        
        private string ctrPtyIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime MtrtyDt {
            get {
                return this.mtrtyDtField;
            }
            set {
                this.mtrtyDtField = value;
            }
        }
        
        /// <remarks/>
        public ActiveCurrencyAndAmount Val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
        
        /// <remarks/>
        public string CtrPtyId {
            get {
                return this.ctrPtyIdField;
            }
            set {
                this.ctrPtyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class ActiveCurrencyAndAmount {
        
        private string ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class ActiveCurrencyAnd24Amount {
        
        private string ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class SecurityIdentificationAndAmount2 {
        
        private string idField;
        
        private ActiveCurrencyAnd24Amount mktValField;
        
        private ProductType6Code finInstrmTpField;
        
        private DebtIssuerType1Code debtIssrTpField;
        
        private bool debtIssrTpFieldSpecified;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public ActiveCurrencyAnd24Amount MktVal {
            get {
                return this.mktValField;
            }
            set {
                this.mktValField = value;
            }
        }
        
        /// <remarks/>
        public ProductType6Code FinInstrmTp {
            get {
                return this.finInstrmTpField;
            }
            set {
                this.finInstrmTpField = value;
            }
        }
        
        /// <remarks/>
        public DebtIssuerType1Code DebtIssrTp {
            get {
                return this.debtIssrTpField;
            }
            set {
                this.debtIssrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebtIssrTpSpecified {
            get {
                return this.debtIssrTpFieldSpecified;
            }
            set {
                this.debtIssrTpFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public enum ProductType6Code {
        
        /// <remarks/>
        BOND,
        
        /// <remarks/>
        CASH,
        
        /// <remarks/>
        OTHR,
        
        /// <remarks/>
        EQUI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public enum DebtIssuerType1Code {
        
        /// <remarks/>
        CORP,
        
        /// <remarks/>
        MUNI,
        
        /// <remarks/>
        SPVS,
        
        /// <remarks/>
        SUPR,
        
        /// <remarks/>
        SVGN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class OtherInvestment1 {
        
        private string descField;
        
        private ActiveCurrencyAndAmount amtField;
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public ActiveCurrencyAndAmount Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class GeneralCollateral3 {
        
        private FinancialInstrument59[] finInstrmIdField;
        
        private string[] elgblFinInstrmIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FinInstrmId")]
        public FinancialInstrument59[] FinInstrmId {
            get {
                return this.finInstrmIdField;
            }
            set {
                this.finInstrmIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ElgblFinInstrmId")]
        public string[] ElgblFinInstrmId {
            get {
                return this.elgblFinInstrmIdField;
            }
            set {
                this.elgblFinInstrmIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class FinancialInstrument59 {
        
        private string idField;
        
        private string issrField;
        
        private string sctrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string Sctr {
            get {
                return this.sctrField;
            }
            set {
                this.sctrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class SpecificCollateral2 {
        
        private FinancialInstrument59 finInstrmIdField;
        
        /// <remarks/>
        public FinancialInstrument59 FinInstrmId {
            get {
                return this.finInstrmIdField;
            }
            set {
                this.finInstrmIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class RepurchaseAgreementType3Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GnlColl", typeof(GeneralCollateral3))]
        [System.Xml.Serialization.XmlElementAttribute("SpcfcColl", typeof(SpecificCollateral2))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02")]
    public partial class RepurchaseAgreement2 {
        
        private System.DateTime mtrtyDtField;
        
        private ActiveCurrencyAndAmount scndLegPricField;
        
        private ActiveCurrencyAndAmount collMktValField;
        
        private string ctrPtyField;
        
        private RepurchaseAgreementType3Choice rpAgrmtTpField;
        
        private string trptyAgtIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime MtrtyDt {
            get {
                return this.mtrtyDtField;
            }
            set {
                this.mtrtyDtField = value;
            }
        }
        
        /// <remarks/>
        public ActiveCurrencyAndAmount ScndLegPric {
            get {
                return this.scndLegPricField;
            }
            set {
                this.scndLegPricField = value;
            }
        }
        
        /// <remarks/>
        public ActiveCurrencyAndAmount CollMktVal {
            get {
                return this.collMktValField;
            }
            set {
                this.collMktValField = value;
            }
        }
        
        /// <remarks/>
        public string CtrPty {
            get {
                return this.ctrPtyField;
            }
            set {
                this.ctrPtyField = value;
            }
        }
        
        /// <remarks/>
        public RepurchaseAgreementType3Choice RpAgrmtTp {
            get {
                return this.rpAgrmtTpField;
            }
            set {
                this.rpAgrmtTpField = value;
            }
        }
        
        /// <remarks/>
        public string TrptyAgtId {
            get {
                return this.trptyAgtIdField;
            }
            set {
                this.trptyAgtIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.061.001.02", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        CntrlBkDpst,
        
        /// <remarks/>
        OthrInvstmts,
        
        /// <remarks/>
        OutrghtInvstmt,
        
        /// <remarks/>
        RpAgrmt,
        
        /// <remarks/>
        UscrdCshDpst,
    }
}
