//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ISO20022.Sese_022_001_07 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07", IsNullable=false)]
    public partial class Document {
        
        private SecuritiesStatusOrStatementQueryStatusAdviceV07 sctiesStsOrStmtQryStsAdvcField;
        
        /// <remarks/>
        public SecuritiesStatusOrStatementQueryStatusAdviceV07 SctiesStsOrStmtQryStsAdvc {
            get {
                return this.sctiesStsOrStmtQryStsAdvcField;
            }
            set {
                this.sctiesStsOrStmtQryStsAdvcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class SecuritiesStatusOrStatementQueryStatusAdviceV07 {
        
        private DocumentIdentification54 qryDtlsField;
        
        private PartyIdentification144 acctOwnrField;
        
        private SecuritiesAccount19 sfkpgAcctField;
        
        private BlockChainAddressWallet3 blckChainAdrOrWlltField;
        
        private StatusOrStatement13Choice stsOrStmtReqdField;
        
        private ProcessingStatus89Choice prcgStsField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        public DocumentIdentification54 QryDtls {
            get {
                return this.qryDtlsField;
            }
            set {
                this.qryDtlsField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification144 AcctOwnr {
            get {
                return this.acctOwnrField;
            }
            set {
                this.acctOwnrField = value;
            }
        }
        
        /// <remarks/>
        public SecuritiesAccount19 SfkpgAcct {
            get {
                return this.sfkpgAcctField;
            }
            set {
                this.sfkpgAcctField = value;
            }
        }
        
        /// <remarks/>
        public BlockChainAddressWallet3 BlckChainAdrOrWllt {
            get {
                return this.blckChainAdrOrWlltField;
            }
            set {
                this.blckChainAdrOrWlltField = value;
            }
        }
        
        /// <remarks/>
        public StatusOrStatement13Choice StsOrStmtReqd {
            get {
                return this.stsOrStmtReqdField;
            }
            set {
                this.stsOrStmtReqdField = value;
            }
        }
        
        /// <remarks/>
        public ProcessingStatus89Choice PrcgSts {
            get {
                return this.prcgStsField;
            }
            set {
                this.prcgStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class DocumentIdentification54 {
        
        private DocumentNumber5Choice msgNbField;
        
        private string refField;
        
        /// <remarks/>
        public DocumentNumber5Choice MsgNb {
            get {
                return this.msgNbField;
            }
            set {
                this.msgNbField = value;
            }
        }
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class DocumentNumber5Choice {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LngNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryNb", typeof(GenericIdentification36))]
        [System.Xml.Serialization.XmlElementAttribute("ShrtNb", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class GenericIdentification36 {
        
        private string idField;
        
        private string issrField;
        
        private string schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class ProprietaryReason4 {
        
        private GenericIdentification30 rsnField;
        
        private string addtlRsnInfField;
        
        /// <remarks/>
        public GenericIdentification30 Rsn {
            get {
                return this.rsnField;
            }
            set {
                this.rsnField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlRsnInf {
            get {
                return this.addtlRsnInfField;
            }
            set {
                this.addtlRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class GenericIdentification30 {
        
        private string idField;
        
        private string issrField;
        
        private string schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class ProprietaryStatusAndReason6 {
        
        private GenericIdentification30 prtryStsField;
        
        private ProprietaryReason4[] prtryRsnField;
        
        /// <remarks/>
        public GenericIdentification30 PrtrySts {
            get {
                return this.prtryStsField;
            }
            set {
                this.prtryStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PrtryRsn")]
        public ProprietaryReason4[] PrtryRsn {
            get {
                return this.prtryRsnField;
            }
            set {
                this.prtryRsnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class RejectionAndRepairReason39Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(RejectionReason77Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public enum RejectionReason77Code {
        
        /// <remarks/>
        SAFE,
        
        /// <remarks/>
        DSEC,
        
        /// <remarks/>
        LATE,
        
        /// <remarks/>
        REFE,
        
        /// <remarks/>
        ADEA,
        
        /// <remarks/>
        OTHR,
        
        /// <remarks/>
        MISM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class RejectionOrRepairReason39 {
        
        private RejectionAndRepairReason39Choice cdField;
        
        private string addtlRsnInfField;
        
        /// <remarks/>
        public RejectionAndRepairReason39Choice Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlRsnInf {
            get {
                return this.addtlRsnInfField;
            }
            set {
                this.addtlRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class RejectionOrRepairStatus44Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
        [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(RejectionOrRepairReason39))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public enum NoReasonCode {
        
        /// <remarks/>
        NORE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class AcknowledgementReason15Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(AcknowledgementReason3Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public enum AcknowledgementReason3Code {
        
        /// <remarks/>
        ADEA,
        
        /// <remarks/>
        SMPG,
        
        /// <remarks/>
        OTHR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class AcknowledgementReason12 {
        
        private AcknowledgementReason15Choice cdField;
        
        private string addtlRsnInfField;
        
        /// <remarks/>
        public AcknowledgementReason15Choice Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlRsnInf {
            get {
                return this.addtlRsnInfField;
            }
            set {
                this.addtlRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class AcknowledgedAcceptedStatus24Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
        [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(AcknowledgementReason12))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class ProcessingStatus89Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AckdAccptd", typeof(AcknowledgedAcceptedStatus24Choice))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(ProprietaryStatusAndReason6))]
        [System.Xml.Serialization.XmlElementAttribute("Rjctd", typeof(RejectionOrRepairStatus44Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class DocumentNumber13 {
        
        private DocumentNumber5Choice nbField;
        
        /// <remarks/>
        public DocumentNumber5Choice Nb {
            get {
                return this.nbField;
            }
            set {
                this.nbField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class Identification31 {
        
        private string acctOwnrTxIdField;
        
        private string acctSvcrTxIdField;
        
        private string mktInfrstrctrTxIdField;
        
        private string ctrPtyMktInfrstrctrTxIdField;
        
        private string prcrTxIdField;
        
        private string cmonIdField;
        
        private string tradIdField;
        
        private string unqTxIdrField;
        
        private string mstrIdField;
        
        private string bsktIdField;
        
        private string indxIdField;
        
        private string listIdField;
        
        private string prgmIdField;
        
        private string poolIdField;
        
        private string corpActnEvtIdField;
        
        /// <remarks/>
        public string AcctOwnrTxId {
            get {
                return this.acctOwnrTxIdField;
            }
            set {
                this.acctOwnrTxIdField = value;
            }
        }
        
        /// <remarks/>
        public string AcctSvcrTxId {
            get {
                return this.acctSvcrTxIdField;
            }
            set {
                this.acctSvcrTxIdField = value;
            }
        }
        
        /// <remarks/>
        public string MktInfrstrctrTxId {
            get {
                return this.mktInfrstrctrTxIdField;
            }
            set {
                this.mktInfrstrctrTxIdField = value;
            }
        }
        
        /// <remarks/>
        public string CtrPtyMktInfrstrctrTxId {
            get {
                return this.ctrPtyMktInfrstrctrTxIdField;
            }
            set {
                this.ctrPtyMktInfrstrctrTxIdField = value;
            }
        }
        
        /// <remarks/>
        public string PrcrTxId {
            get {
                return this.prcrTxIdField;
            }
            set {
                this.prcrTxIdField = value;
            }
        }
        
        /// <remarks/>
        public string CmonId {
            get {
                return this.cmonIdField;
            }
            set {
                this.cmonIdField = value;
            }
        }
        
        /// <remarks/>
        public string TradId {
            get {
                return this.tradIdField;
            }
            set {
                this.tradIdField = value;
            }
        }
        
        /// <remarks/>
        public string UnqTxIdr {
            get {
                return this.unqTxIdrField;
            }
            set {
                this.unqTxIdrField = value;
            }
        }
        
        /// <remarks/>
        public string MstrId {
            get {
                return this.mstrIdField;
            }
            set {
                this.mstrIdField = value;
            }
        }
        
        /// <remarks/>
        public string BsktId {
            get {
                return this.bsktIdField;
            }
            set {
                this.bsktIdField = value;
            }
        }
        
        /// <remarks/>
        public string IndxId {
            get {
                return this.indxIdField;
            }
            set {
                this.indxIdField = value;
            }
        }
        
        /// <remarks/>
        public string ListId {
            get {
                return this.listIdField;
            }
            set {
                this.listIdField = value;
            }
        }
        
        /// <remarks/>
        public string PrgmId {
            get {
                return this.prgmIdField;
            }
            set {
                this.prgmIdField = value;
            }
        }
        
        /// <remarks/>
        public string PoolId {
            get {
                return this.poolIdField;
            }
            set {
                this.poolIdField = value;
            }
        }
        
        /// <remarks/>
        public string CorpActnEvtId {
            get {
                return this.corpActnEvtIdField;
            }
            set {
                this.corpActnEvtIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class DocumentNumber21 {
        
        private DocumentNumber5Choice nbField;
        
        private Identification31[] refsField;
        
        /// <remarks/>
        public DocumentNumber5Choice Nb {
            get {
                return this.nbField;
            }
            set {
                this.nbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Refs")]
        public Identification31[] Refs {
            get {
                return this.refsField;
            }
            set {
                this.refsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class StatusOrStatement13Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stmt", typeof(DocumentNumber13))]
        [System.Xml.Serialization.XmlElementAttribute("StsAdvc", typeof(DocumentNumber21))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class BlockChainAddressWallet3 {
        
        private string idField;
        
        private GenericIdentification30 tpField;
        
        private string nmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public GenericIdentification30 Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class SecuritiesAccount19 {
        
        private string idField;
        
        private GenericIdentification30 tpField;
        
        private string nmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public GenericIdentification30 Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class PartyIdentification127Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification36))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07")]
    public partial class PartyIdentification144 {
        
        private PartyIdentification127Choice idField;
        
        private string lEIField;
        
        /// <remarks/>
        public PartyIdentification127Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LEI {
            get {
                return this.lEIField;
            }
            set {
                this.lEIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.022.001.07", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        LngNb,
        
        /// <remarks/>
        PrtryNb,
        
        /// <remarks/>
        ShrtNb,
    }
}
