//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ISO20022.Sese_040_002_04 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04", IsNullable=false)]
    public partial class Document {
        
        private SecuritiesSettlementTransactionCounterpartyResponse002V04 sctiesSttlmTxCtrPtyRspnField;
        
        /// <remarks/>
        public SecuritiesSettlementTransactionCounterpartyResponse002V04 SctiesSttlmTxCtrPtyRspn {
            get {
                return this.sctiesSttlmTxCtrPtyRspnField;
            }
            set {
                this.sctiesSttlmTxCtrPtyRspnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class SecuritiesSettlementTransactionCounterpartyResponse002V04 {
        
        private TransactionIdentification7 txIdField;
        
        private ResponseStatus8Choice rspnStsField;
        
        private TransactionDetails157 txDtlsField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        public TransactionIdentification7 TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
            }
        }
        
        /// <remarks/>
        public ResponseStatus8Choice RspnSts {
            get {
                return this.rspnStsField;
            }
            set {
                this.rspnStsField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDetails157 TxDtls {
            get {
                return this.txDtlsField;
            }
            set {
                this.txDtlsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class TransactionIdentification7 {
        
        private string acctOwnrTxIdField;
        
        private string acctSvcrTxIdField;
        
        private string mktInfrstrctrTxIdField;
        
        private string prcrTxIdField;
        
        /// <remarks/>
        public string AcctOwnrTxId {
            get {
                return this.acctOwnrTxIdField;
            }
            set {
                this.acctOwnrTxIdField = value;
            }
        }
        
        /// <remarks/>
        public string AcctSvcrTxId {
            get {
                return this.acctSvcrTxIdField;
            }
            set {
                this.acctSvcrTxIdField = value;
            }
        }
        
        /// <remarks/>
        public string MktInfrstrctrTxId {
            get {
                return this.mktInfrstrctrTxIdField;
            }
            set {
                this.mktInfrstrctrTxIdField = value;
            }
        }
        
        /// <remarks/>
        public string PrcrTxId {
            get {
                return this.prcrTxIdField;
            }
            set {
                this.prcrTxIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class PartyIdentification176Choice {
        
        private object itemField;
        
        private ItemChoiceType5 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Ctry", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NmAndAdr", typeof(NameAndAddress12))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification84))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType5 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class NameAndAddress12 {
        
        private string nmField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class GenericIdentification84 {
        
        private string idField;
        
        private string issrField;
        
        private string schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04", IncludeInSchema=false)]
    public enum ItemChoiceType5 {
        
        /// <remarks/>
        AnyBIC,
        
        /// <remarks/>
        Ctry,
        
        /// <remarks/>
        NmAndAdr,
        
        /// <remarks/>
        PrtryId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class PartyIdentification170 {
        
        private PartyIdentification176Choice idField;
        
        private string lEIField;
        
        /// <remarks/>
        public PartyIdentification176Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LEI {
            get {
                return this.lEIField;
            }
            set {
                this.lEIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class PartyIdentification137Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NmAndAdr", typeof(NameAndAddress12))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification84))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class PartyIdentificationAndAccount215 {
        
        private PartyIdentification137Choice idField;
        
        private string lEIField;
        
        private SecuritiesAccount30 sfkpgAcctField;
        
        private BlockChainAddressWallet7 blckChainAdrOrWlltField;
        
        private string prcgIdField;
        
        /// <remarks/>
        public PartyIdentification137Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LEI {
            get {
                return this.lEIField;
            }
            set {
                this.lEIField = value;
            }
        }
        
        /// <remarks/>
        public SecuritiesAccount30 SfkpgAcct {
            get {
                return this.sfkpgAcctField;
            }
            set {
                this.sfkpgAcctField = value;
            }
        }
        
        /// <remarks/>
        public BlockChainAddressWallet7 BlckChainAdrOrWllt {
            get {
                return this.blckChainAdrOrWlltField;
            }
            set {
                this.blckChainAdrOrWlltField = value;
            }
        }
        
        /// <remarks/>
        public string PrcgId {
            get {
                return this.prcgIdField;
            }
            set {
                this.prcgIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class SecuritiesAccount30 {
        
        private string idField;
        
        private GenericIdentification47 tpField;
        
        private string nmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public GenericIdentification47 Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class GenericIdentification47 {
        
        private string idField;
        
        private string issrField;
        
        private string schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class BlockChainAddressWallet7 {
        
        private string idField;
        
        private GenericIdentification47 tpField;
        
        private string nmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public GenericIdentification47 Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class PartyIdentification145Choice {
        
        private object itemField;
        
        private ItemChoiceType4 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Ctry", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NmAndAdr", typeof(NameAndAddress12))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType4 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04", IncludeInSchema=false)]
    public enum ItemChoiceType4 {
        
        /// <remarks/>
        AnyBIC,
        
        /// <remarks/>
        Ctry,
        
        /// <remarks/>
        NmAndAdr,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class PartyIdentification191 {
        
        private PartyIdentification145Choice idField;
        
        private string lEIField;
        
        private string prcgIdField;
        
        /// <remarks/>
        public PartyIdentification145Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string LEI {
            get {
                return this.lEIField;
            }
            set {
                this.lEIField = value;
            }
        }
        
        /// <remarks/>
        public string PrcgId {
            get {
                return this.prcgIdField;
            }
            set {
                this.prcgIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class SettlementParties109 {
        
        private PartyIdentification191 dpstryField;
        
        private PartyIdentificationAndAccount215 pty1Field;
        
        private PartyIdentificationAndAccount215 pty2Field;
        
        private PartyIdentificationAndAccount215 pty3Field;
        
        private PartyIdentificationAndAccount215 pty4Field;
        
        private PartyIdentificationAndAccount215 pty5Field;
        
        /// <remarks/>
        public PartyIdentification191 Dpstry {
            get {
                return this.dpstryField;
            }
            set {
                this.dpstryField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationAndAccount215 Pty1 {
            get {
                return this.pty1Field;
            }
            set {
                this.pty1Field = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationAndAccount215 Pty2 {
            get {
                return this.pty2Field;
            }
            set {
                this.pty2Field = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationAndAccount215 Pty3 {
            get {
                return this.pty3Field;
            }
            set {
                this.pty3Field = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationAndAccount215 Pty4 {
            get {
                return this.pty4Field;
            }
            set {
                this.pty4Field = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentificationAndAccount215 Pty5 {
            get {
                return this.pty5Field;
            }
            set {
                this.pty5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class TradeDateCode4Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(DateType3Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public enum DateType3Code {
        
        /// <remarks/>
        VARI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class TradeDate9Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(DateAndDateTime2Choice))]
        [System.Xml.Serialization.XmlElementAttribute("DtCd", typeof(TradeDateCode4Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class DateAndDateTime2Choice {
        
        private System.DateTime itemField;
        
        private ItemChoiceType3 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("DtTm", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public System.DateTime Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04", IncludeInSchema=false)]
    public enum ItemChoiceType3 {
        
        /// <remarks/>
        Dt,
        
        /// <remarks/>
        DtTm,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class SettlementDateCode11Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(DateType4Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public enum DateType4Code {
        
        /// <remarks/>
        OPEN,
        
        /// <remarks/>
        UKWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class SettlementDate32Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(DateAndDateTime2Choice))]
        [System.Xml.Serialization.XmlElementAttribute("DtCd", typeof(SettlementDateCode11Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class RestrictedFINActiveOrHistoricCurrencyAndAmount {
        
        private string ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class RestrictedFINActiveCurrencyAndAmount {
        
        private string ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class AmountAndDirection67 {
        
        private RestrictedFINActiveCurrencyAndAmount amtField;
        
        private CreditDebitCode cdtDbtIndField;
        
        private RestrictedFINActiveOrHistoricCurrencyAndAmount orgnlCcyAndOrdrdAmtField;
        
        /// <remarks/>
        public RestrictedFINActiveCurrencyAndAmount Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public CreditDebitCode CdtDbtInd {
            get {
                return this.cdtDbtIndField;
            }
            set {
                this.cdtDbtIndField = value;
            }
        }
        
        /// <remarks/>
        public RestrictedFINActiveOrHistoricCurrencyAndAmount OrgnlCcyAndOrdrdAmt {
            get {
                return this.orgnlCcyAndOrdrdAmtField;
            }
            set {
                this.orgnlCcyAndOrdrdAmtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public enum CreditDebitCode {
        
        /// <remarks/>
        CRDT,
        
        /// <remarks/>
        DBIT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class OriginalAndCurrentQuantities4 {
        
        private decimal faceAmtField;
        
        private decimal amtsdValField;
        
        /// <remarks/>
        public decimal FaceAmt {
            get {
                return this.faceAmtField;
            }
            set {
                this.faceAmtField = value;
            }
        }
        
        /// <remarks/>
        public decimal AmtsdVal {
            get {
                return this.amtsdValField;
            }
            set {
                this.amtsdValField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class FinancialInstrumentQuantity36Choice {
        
        private decimal itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AmtsdVal", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("DgtlTknUnit", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("FaceAmt", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public decimal Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        AmtsdVal,
        
        /// <remarks/>
        DgtlTknUnit,
        
        /// <remarks/>
        FaceAmt,
        
        /// <remarks/>
        Unit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class Quantity54Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrgnlAndCurFace", typeof(OriginalAndCurrentQuantities4))]
        [System.Xml.Serialization.XmlElementAttribute("Qty", typeof(FinancialInstrumentQuantity36Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class IdentificationSource4Choice {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class OtherIdentification2 {
        
        private string idField;
        
        private string sfxField;
        
        private IdentificationSource4Choice tpField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Sfx {
            get {
                return this.sfxField;
            }
            set {
                this.sfxField = value;
            }
        }
        
        /// <remarks/>
        public IdentificationSource4Choice Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class SecurityIdentification20 {
        
        private string iSINField;
        
        private OtherIdentification2[] othrIdField;
        
        private string descField;
        
        /// <remarks/>
        public string ISIN {
            get {
                return this.iSINField;
            }
            set {
                this.iSINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OthrId")]
        public OtherIdentification2[] OthrId {
            get {
                return this.othrIdField;
            }
            set {
                this.othrIdField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class TransactionDetails157 {
        
        private SecurityIdentification20 finInstrmIdField;
        
        private ReceiveDelivery1Code sctiesMvmntTpField;
        
        private DeliveryReceiptType2Code pmtField;
        
        private Quantity54Choice sttlmQtyField;
        
        private SecuritiesAccount30 sfkpgAcctField;
        
        private BlockChainAddressWallet7 blckChainAdrOrWlltField;
        
        private AmountAndDirection67 sttlmAmtField;
        
        private SettlementDate32Choice sttlmDtField;
        
        private TradeDate9Choice tradDtField;
        
        private SettlementParties109 dlvrgSttlmPtiesField;
        
        private SettlementParties109 rcvgSttlmPtiesField;
        
        private PartyIdentification170 invstrField;
        
        /// <remarks/>
        public SecurityIdentification20 FinInstrmId {
            get {
                return this.finInstrmIdField;
            }
            set {
                this.finInstrmIdField = value;
            }
        }
        
        /// <remarks/>
        public ReceiveDelivery1Code SctiesMvmntTp {
            get {
                return this.sctiesMvmntTpField;
            }
            set {
                this.sctiesMvmntTpField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryReceiptType2Code Pmt {
            get {
                return this.pmtField;
            }
            set {
                this.pmtField = value;
            }
        }
        
        /// <remarks/>
        public Quantity54Choice SttlmQty {
            get {
                return this.sttlmQtyField;
            }
            set {
                this.sttlmQtyField = value;
            }
        }
        
        /// <remarks/>
        public SecuritiesAccount30 SfkpgAcct {
            get {
                return this.sfkpgAcctField;
            }
            set {
                this.sfkpgAcctField = value;
            }
        }
        
        /// <remarks/>
        public BlockChainAddressWallet7 BlckChainAdrOrWllt {
            get {
                return this.blckChainAdrOrWlltField;
            }
            set {
                this.blckChainAdrOrWlltField = value;
            }
        }
        
        /// <remarks/>
        public AmountAndDirection67 SttlmAmt {
            get {
                return this.sttlmAmtField;
            }
            set {
                this.sttlmAmtField = value;
            }
        }
        
        /// <remarks/>
        public SettlementDate32Choice SttlmDt {
            get {
                return this.sttlmDtField;
            }
            set {
                this.sttlmDtField = value;
            }
        }
        
        /// <remarks/>
        public TradeDate9Choice TradDt {
            get {
                return this.tradDtField;
            }
            set {
                this.tradDtField = value;
            }
        }
        
        /// <remarks/>
        public SettlementParties109 DlvrgSttlmPties {
            get {
                return this.dlvrgSttlmPtiesField;
            }
            set {
                this.dlvrgSttlmPtiesField = value;
            }
        }
        
        /// <remarks/>
        public SettlementParties109 RcvgSttlmPties {
            get {
                return this.rcvgSttlmPtiesField;
            }
            set {
                this.rcvgSttlmPtiesField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification170 Invstr {
            get {
                return this.invstrField;
            }
            set {
                this.invstrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public enum ReceiveDelivery1Code {
        
        /// <remarks/>
        DELI,
        
        /// <remarks/>
        RECE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public enum DeliveryReceiptType2Code {
        
        /// <remarks/>
        FREE,
        
        /// <remarks/>
        APMT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class NoSpecifiedReason1 {
        
        private NoReasonCode noSpcfdRsnField;
        
        /// <remarks/>
        public NoReasonCode NoSpcfdRsn {
            get {
                return this.noSpcfdRsnField;
            }
            set {
                this.noSpcfdRsnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public enum NoReasonCode {
        
        /// <remarks/>
        NORE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class PendingStatus20Choice {
        
        private NoSpecifiedReason1 itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fwdd", typeof(NoSpecifiedReason1))]
        [System.Xml.Serialization.XmlElementAttribute("UdrInvstgtn", typeof(NoSpecifiedReason1))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public NoSpecifiedReason1 Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Fwdd,
        
        /// <remarks/>
        UdrInvstgtn,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class RejectionReason40 {
        
        private ConsentOrRejectionReason5Choice cdField;
        
        private string addtlRsnInfField;
        
        /// <remarks/>
        public ConsentOrRejectionReason5Choice Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlRsnInf {
            get {
                return this.addtlRsnInfField;
            }
            set {
                this.addtlRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class ConsentOrRejectionReason5Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(CounterpartyResponseStatusReason1Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification47))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public enum CounterpartyResponseStatusReason1Code {
        
        /// <remarks/>
        CPTR,
        
        /// <remarks/>
        CPCX,
        
        /// <remarks/>
        CPMD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class RejectionStatus27Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
        [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(RejectionReason40))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class ConsentReason5 {
        
        private ConsentOrRejectionReason5Choice cdField;
        
        private string addtlRsnInfField;
        
        /// <remarks/>
        public ConsentOrRejectionReason5Choice Cd {
            get {
                return this.cdField;
            }
            set {
                this.cdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlRsnInf {
            get {
                return this.addtlRsnInfField;
            }
            set {
                this.addtlRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class ConsentStatus5Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
        [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(ConsentReason5))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:sese.040.002.04")]
    public partial class ResponseStatus8Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cnsntd", typeof(ConsentStatus5Choice))]
        [System.Xml.Serialization.XmlElementAttribute("Pdg", typeof(PendingStatus20Choice))]
        [System.Xml.Serialization.XmlElementAttribute("Rjctd", typeof(RejectionStatus27Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
