//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ISO20022.Seev_006_001_11 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11", IsNullable=false)]
    public partial class Document {
        
        private MeetingInstructionStatusV11 mtgInstrStsField;
        
        /// <remarks/>
        public MeetingInstructionStatusV11 MtgInstrSts {
            get {
                return this.mtgInstrStsField;
            }
            set {
                this.mtgInstrStsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class MeetingInstructionStatusV11 {
        
        private InstructionType2Choice instrTpField;
        
        private MeetingReference10 mtgRefField;
        
        private SecurityIdentification19 finInstrmIdField;
        
        private InstructionTypeStatus7Choice instrTpStsField;
        
        private EligiblePosition17 posField;
        
        private PartyIdentification226Choice cnfrmgPtyField;
        
        private PartyIdentification226Choice voteCstgPtyField;
        
        private PartyIdentification246Choice[] rghtsHldrField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        public InstructionType2Choice InstrTp {
            get {
                return this.instrTpField;
            }
            set {
                this.instrTpField = value;
            }
        }
        
        /// <remarks/>
        public MeetingReference10 MtgRef {
            get {
                return this.mtgRefField;
            }
            set {
                this.mtgRefField = value;
            }
        }
        
        /// <remarks/>
        public SecurityIdentification19 FinInstrmId {
            get {
                return this.finInstrmIdField;
            }
            set {
                this.finInstrmIdField = value;
            }
        }
        
        /// <remarks/>
        public InstructionTypeStatus7Choice InstrTpSts {
            get {
                return this.instrTpStsField;
            }
            set {
                this.instrTpStsField = value;
            }
        }
        
        /// <remarks/>
        public EligiblePosition17 Pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification226Choice CnfrmgPty {
            get {
                return this.cnfrmgPtyField;
            }
            set {
                this.cnfrmgPtyField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification226Choice VoteCstgPty {
            get {
                return this.voteCstgPtyField;
            }
            set {
                this.voteCstgPtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RghtsHldr")]
        public PartyIdentification246Choice[] RghtsHldr {
            get {
                return this.rghtsHldrField;
            }
            set {
                this.rghtsHldrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class InstructionType2Choice {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstrCxlId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("InstrId", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        InstrCxlId,
        
        /// <remarks/>
        InstrId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification250 {
        
        private PersonName3 nmAndAdrField;
        
        private string emailAdrField;
        
        private NaturalPersonIdentification1 idField;
        
        private string ntltyField;
        
        private DateAndPlaceOfBirth2 dtAndPlcOfBirthField;
        
        private string cpnyRegrShrhldrIdField;
        
        /// <remarks/>
        public PersonName3 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public NaturalPersonIdentification1 Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ntlty {
            get {
                return this.ntltyField;
            }
            set {
                this.ntltyField = value;
            }
        }
        
        /// <remarks/>
        public DateAndPlaceOfBirth2 DtAndPlcOfBirth {
            get {
                return this.dtAndPlcOfBirthField;
            }
            set {
                this.dtAndPlcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CpnyRegrShrhldrId {
            get {
                return this.cpnyRegrShrhldrIdField;
            }
            set {
                this.cpnyRegrShrhldrIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PersonName3 {
        
        private NamePrefix2Code nmPrfxField;
        
        private bool nmPrfxFieldSpecified;
        
        private string frstNmField;
        
        private string srnmField;
        
        private PostalAddress26 adrField;
        
        /// <remarks/>
        public NamePrefix2Code NmPrfx {
            get {
                return this.nmPrfxField;
            }
            set {
                this.nmPrfxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NmPrfxSpecified {
            get {
                return this.nmPrfxFieldSpecified;
            }
            set {
                this.nmPrfxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string FrstNm {
            get {
                return this.frstNmField;
            }
            set {
                this.frstNmField = value;
            }
        }
        
        /// <remarks/>
        public string Srnm {
            get {
                return this.srnmField;
            }
            set {
                this.srnmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress26 Adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum NamePrefix2Code {
        
        /// <remarks/>
        DOCT,
        
        /// <remarks/>
        MADM,
        
        /// <remarks/>
        MISS,
        
        /// <remarks/>
        MIST,
        
        /// <remarks/>
        MIKS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PostalAddress26 {
        
        private AddressType2Code adrTpField;
        
        private bool adrTpFieldSpecified;
        
        private string[] adrLineField;
        
        private string strtNmField;
        
        private string bldgNbField;
        
        private string pstBxField;
        
        private string pstCdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        /// <remarks/>
        public AddressType2Code AdrTp {
            get {
                return this.adrTpField;
            }
            set {
                this.adrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrTpSpecified {
            get {
                return this.adrTpFieldSpecified;
            }
            set {
                this.adrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string BldgNb {
            get {
                return this.bldgNbField;
            }
            set {
                this.bldgNbField = value;
            }
        }
        
        /// <remarks/>
        public string PstBx {
            get {
                return this.pstBxField;
            }
            set {
                this.pstBxField = value;
            }
        }
        
        /// <remarks/>
        public string PstCd {
            get {
                return this.pstCdField;
            }
            set {
                this.pstCdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum AddressType2Code {
        
        /// <remarks/>
        ADDR,
        
        /// <remarks/>
        PBOX,
        
        /// <remarks/>
        HOME,
        
        /// <remarks/>
        BIZZ,
        
        /// <remarks/>
        MLTO,
        
        /// <remarks/>
        DLVY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class NaturalPersonIdentification1 {
        
        private string idField;
        
        private IdentificationType45Choice idTpField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public IdentificationType45Choice IdTp {
            get {
                return this.idTpField;
            }
            set {
                this.idTpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class IdentificationType45Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(TypeOfIdentification4Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum TypeOfIdentification4Code {
        
        /// <remarks/>
        ARNU,
        
        /// <remarks/>
        CUST,
        
        /// <remarks/>
        CORP,
        
        /// <remarks/>
        DRLC,
        
        /// <remarks/>
        IDCD,
        
        /// <remarks/>
        NRIN,
        
        /// <remarks/>
        CCPT,
        
        /// <remarks/>
        SOCS,
        
        /// <remarks/>
        TXID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class GenericIdentification30 {
        
        private string idField;
        
        private string issrField;
        
        private string schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class DateAndPlaceOfBirth2 {
        
        private System.DateTime birthDtField;
        
        private string prvcOfBirthField;
        
        private string cityOfBirthField;
        
        private string ctryOfBirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDt {
            get {
                return this.birthDtField;
            }
            set {
                this.birthDtField = value;
            }
        }
        
        /// <remarks/>
        public string PrvcOfBirth {
            get {
                return this.prvcOfBirthField;
            }
            set {
                this.prvcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CityOfBirth {
            get {
                return this.cityOfBirthField;
            }
            set {
                this.cityOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfBirth {
            get {
                return this.ctryOfBirthField;
            }
            set {
                this.ctryOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification269 {
        
        private PersonName2 nmAndAdrField;
        
        private string emailAdrField;
        
        private PartyIdentification198Choice idField;
        
        private string cpnyRegrShrhldrIdField;
        
        private string ctryOfIncorprtnField;
        
        /// <remarks/>
        public PersonName2 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification198Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CpnyRegrShrhldrId {
            get {
                return this.cpnyRegrShrhldrIdField;
            }
            set {
                this.cpnyRegrShrhldrIdField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfIncorprtn {
            get {
                return this.ctryOfIncorprtnField;
            }
            set {
                this.ctryOfIncorprtnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PersonName2 {
        
        private string nmField;
        
        private PostalAddress26 adrField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress26 Adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification198Choice {
        
        private object itemField;
        
        private ItemChoiceType3 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ClntId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NtlRegnNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification36))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class GenericIdentification36 {
        
        private string idField;
        
        private string issrField;
        
        private string schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11", IncludeInSchema=false)]
    public enum ItemChoiceType3 {
        
        /// <remarks/>
        AnyBIC,
        
        /// <remarks/>
        ClntId,
        
        /// <remarks/>
        LEI,
        
        /// <remarks/>
        NtlRegnNb,
        
        /// <remarks/>
        PrtryId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification246Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LglPrsn", typeof(PartyIdentification269))]
        [System.Xml.Serialization.XmlElementAttribute("NtrlPrsn", typeof(PartyIdentification250))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PersonName1 {
        
        private string frstNmField;
        
        private string srnmField;
        
        private PostalAddress26 adrField;
        
        /// <remarks/>
        public string FrstNm {
            get {
                return this.frstNmField;
            }
            set {
                this.frstNmField = value;
            }
        }
        
        /// <remarks/>
        public string Srnm {
            get {
                return this.srnmField;
            }
            set {
                this.srnmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress26 Adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification222 {
        
        private PersonName1 nmAndAdrField;
        
        private string emailAdrField;
        
        private NaturalPersonIdentification1 idField;
        
        /// <remarks/>
        public PersonName1 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public NaturalPersonIdentification1 Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification224 {
        
        private PersonName2 nmAndAdrField;
        
        private string emailAdrField;
        
        private PartyIdentification198Choice idField;
        
        /// <remarks/>
        public PersonName2 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification198Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification226Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LglPrsn", typeof(PartyIdentification224))]
        [System.Xml.Serialization.XmlElementAttribute("NtrlPrsn", typeof(PartyIdentification222))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class FinancialInstrumentQuantity45Choice {
        
        private decimal itemField;
        
        private ItemChoiceType4 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DgtlTknUnit", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("FaceAmt", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public decimal Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType4 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11", IncludeInSchema=false)]
    public enum ItemChoiceType4 {
        
        /// <remarks/>
        DgtlTknUnit,
        
        /// <remarks/>
        FaceAmt,
        
        /// <remarks/>
        Unit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class SignedQuantityFormat14 {
        
        private ShortLong1Code shrtLngPosField;
        
        private FinancialInstrumentQuantity45Choice qtyField;
        
        /// <remarks/>
        public ShortLong1Code ShrtLngPos {
            get {
                return this.shrtLngPosField;
            }
            set {
                this.shrtLngPosField = value;
            }
        }
        
        /// <remarks/>
        public FinancialInstrumentQuantity45Choice Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum ShortLong1Code {
        
        /// <remarks/>
        SHOR,
        
        /// <remarks/>
        LONG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class HoldingBalance13 {
        
        private SignedQuantityFormat14 balField;
        
        private SecuritiesEntryType3Code balTpField;
        
        /// <remarks/>
        public SignedQuantityFormat14 Bal {
            get {
                return this.balField;
            }
            set {
                this.balField = value;
            }
        }
        
        /// <remarks/>
        public SecuritiesEntryType3Code BalTp {
            get {
                return this.balTpField;
            }
            set {
                this.balTpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum SecuritiesEntryType3Code {
        
        /// <remarks/>
        ELIG,
        
        /// <remarks/>
        UNBA,
        
        /// <remarks/>
        INBA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification238 {
        
        private PersonName3 nmAndAdrField;
        
        private string emailAdrField;
        
        private NaturalPersonIdentification1 idField;
        
        private string ntltyField;
        
        private DateAndPlaceOfBirth2 dtAndPlcOfBirthField;
        
        /// <remarks/>
        public PersonName3 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public NaturalPersonIdentification1 Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ntlty {
            get {
                return this.ntltyField;
            }
            set {
                this.ntltyField = value;
            }
        }
        
        /// <remarks/>
        public DateAndPlaceOfBirth2 DtAndPlcOfBirth {
            get {
                return this.dtAndPlcOfBirthField;
            }
            set {
                this.dtAndPlcOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification221 {
        
        private PersonName2 nmAndAdrField;
        
        private string emailAdrField;
        
        private PartyIdentification198Choice idField;
        
        /// <remarks/>
        public PersonName2 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification198Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification231Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LglPrsn", typeof(PartyIdentification221))]
        [System.Xml.Serialization.XmlElementAttribute("NtrlPrsn", typeof(PartyIdentification238))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class EligiblePosition17 {
        
        private string acctIdField;
        
        private string blckChainAdrOrWlltField;
        
        private PartyIdentification231Choice acctOwnrField;
        
        private HoldingBalance13[] hldgBalField;
        
        /// <remarks/>
        public string AcctId {
            get {
                return this.acctIdField;
            }
            set {
                this.acctIdField = value;
            }
        }
        
        /// <remarks/>
        public string BlckChainAdrOrWllt {
            get {
                return this.blckChainAdrOrWlltField;
            }
            set {
                this.blckChainAdrOrWlltField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification231Choice AcctOwnr {
            get {
                return this.acctOwnrField;
            }
            set {
                this.acctOwnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HldgBal")]
        public HoldingBalance13[] HldgBal {
            get {
                return this.hldgBalField;
            }
            set {
                this.hldgBalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class DetailedInstructionCancellationStatus15 {
        
        private string snglInstrCxlIdField;
        
        private string acctIdField;
        
        private string subAcctIdField;
        
        private CancellationStatus32Choice instrCxlStsField;
        
        /// <remarks/>
        public string SnglInstrCxlId {
            get {
                return this.snglInstrCxlIdField;
            }
            set {
                this.snglInstrCxlIdField = value;
            }
        }
        
        /// <remarks/>
        public string AcctId {
            get {
                return this.acctIdField;
            }
            set {
                this.acctIdField = value;
            }
        }
        
        /// <remarks/>
        public string SubAcctId {
            get {
                return this.subAcctIdField;
            }
            set {
                this.subAcctIdField = value;
            }
        }
        
        /// <remarks/>
        public CancellationStatus32Choice InstrCxlSts {
            get {
                return this.instrCxlStsField;
            }
            set {
                this.instrCxlStsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class CancellationStatus32Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PdgCxl", typeof(PendingCancellationStatus12Choice))]
        [System.Xml.Serialization.XmlElementAttribute("PrcgSts", typeof(CancellationProcessingStatus2))]
        [System.Xml.Serialization.XmlElementAttribute("Rjctd", typeof(RejectedStatus31Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PendingCancellationStatus12Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
        [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(PendingCancellationStatusReason10))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum NoReasonCode {
        
        /// <remarks/>
        NORE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PendingCancellationStatusReason10 {
        
        private PendingCancellationReason7Choice rsnCdField;
        
        private string addtlRsnInfField;
        
        /// <remarks/>
        public PendingCancellationReason7Choice RsnCd {
            get {
                return this.rsnCdField;
            }
            set {
                this.rsnCdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlRsnInf {
            get {
                return this.addtlRsnInfField;
            }
            set {
                this.addtlRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PendingCancellationReason7Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(PendingCancellationReason6Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum PendingCancellationReason6Code {
        
        /// <remarks/>
        DQUA,
        
        /// <remarks/>
        LATE,
        
        /// <remarks/>
        OTHR,
        
        /// <remarks/>
        ADEA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class CancellationProcessingStatus2 {
        
        private CancellationStatus6Code stsField;
        
        private string addtlInfField;
        
        /// <remarks/>
        public CancellationStatus6Code Sts {
            get {
                return this.stsField;
            }
            set {
                this.stsField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlInf {
            get {
                return this.addtlInfField;
            }
            set {
                this.addtlInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum CancellationStatus6Code {
        
        /// <remarks/>
        PACK,
        
        /// <remarks/>
        CAND,
        
        /// <remarks/>
        RCIS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class RejectedStatus31Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
        [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(RejectedStatusReason28))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class RejectedStatusReason28 {
        
        private RejectedReason29Choice rsnCdField;
        
        private string addtlRsnInfField;
        
        /// <remarks/>
        public RejectedReason29Choice RsnCd {
            get {
                return this.rsnCdField;
            }
            set {
                this.rsnCdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlRsnInf {
            get {
                return this.addtlRsnInfField;
            }
            set {
                this.addtlRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class RejectedReason29Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(RejectionReason51Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum RejectionReason51Code {
        
        /// <remarks/>
        ADEA,
        
        /// <remarks/>
        DQUA,
        
        /// <remarks/>
        DCAN,
        
        /// <remarks/>
        DPRG,
        
        /// <remarks/>
        DSEC,
        
        /// <remarks/>
        EVNM,
        
        /// <remarks/>
        INIR,
        
        /// <remarks/>
        LATE,
        
        /// <remarks/>
        OTHR,
        
        /// <remarks/>
        RBIS,
        
        /// <remarks/>
        SAFE,
        
        /// <remarks/>
        ULNK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class CancellationStatus31Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DtldCxlSts", typeof(DetailedInstructionCancellationStatus15))]
        [System.Xml.Serialization.XmlElementAttribute("GblCxlSts", typeof(CancellationStatus32Choice))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PendingReason67Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(PendingReason25Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum PendingReason25Code {
        
        /// <remarks/>
        ADEA,
        
        /// <remarks/>
        ADDM,
        
        /// <remarks/>
        DQUA,
        
        /// <remarks/>
        DREM,
        
        /// <remarks/>
        FULL,
        
        /// <remarks/>
        IPOA,
        
        /// <remarks/>
        IPOS,
        
        /// <remarks/>
        LACK,
        
        /// <remarks/>
        LATE,
        
        /// <remarks/>
        NPOS,
        
        /// <remarks/>
        IREG,
        
        /// <remarks/>
        OTHR,
        
        /// <remarks/>
        PRXY,
        
        /// <remarks/>
        PENR,
        
        /// <remarks/>
        IPED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PendingStatusReason26 {
        
        private PendingReason67Choice rsnCdField;
        
        private string addtlRsnInfField;
        
        /// <remarks/>
        public PendingReason67Choice RsnCd {
            get {
                return this.rsnCdField;
            }
            set {
                this.rsnCdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlRsnInf {
            get {
                return this.addtlRsnInfField;
            }
            set {
                this.addtlRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PendingStatus70Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
        [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(PendingStatusReason26))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class RejectedReason57Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(RejectionReason82Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum RejectionReason82Code {
        
        /// <remarks/>
        ADEA,
        
        /// <remarks/>
        ADDM,
        
        /// <remarks/>
        MCAN,
        
        /// <remarks/>
        DQUA,
        
        /// <remarks/>
        DREM,
        
        /// <remarks/>
        DSEC,
        
        /// <remarks/>
        EVNM,
        
        /// <remarks/>
        FULL,
        
        /// <remarks/>
        IPOA,
        
        /// <remarks/>
        IPOS,
        
        /// <remarks/>
        IREG,
        
        /// <remarks/>
        LATE,
        
        /// <remarks/>
        NPOS,
        
        /// <remarks/>
        OTHR,
        
        /// <remarks/>
        PART,
        
        /// <remarks/>
        PRXY,
        
        /// <remarks/>
        RBIS,
        
        /// <remarks/>
        RESN,
        
        /// <remarks/>
        SAFE,
        
        /// <remarks/>
        SPLT,
        
        /// <remarks/>
        ULNK,
        
        /// <remarks/>
        OPTY,
        
        /// <remarks/>
        LACK,
        
        /// <remarks/>
        LIST,
        
        /// <remarks/>
        NOSL,
        
        /// <remarks/>
        PMNS,
        
        /// <remarks/>
        IPED,
        
        /// <remarks/>
        DUPL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class RejectedStatusReason54 {
        
        private RejectedReason57Choice rsnCdField;
        
        private string addtlRsnInfField;
        
        /// <remarks/>
        public RejectedReason57Choice RsnCd {
            get {
                return this.rsnCdField;
            }
            set {
                this.rsnCdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlRsnInf {
            get {
                return this.addtlRsnInfField;
            }
            set {
                this.addtlRsnInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class RejectedStatus55Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoSpcfdRsn", typeof(NoReasonCode))]
        [System.Xml.Serialization.XmlElementAttribute("Rsn", typeof(RejectedStatusReason54))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class InstructionProcessingStatus6 {
        
        private Status11Code stsField;
        
        private string attndncCardNbField;
        
        private string addtlInfField;
        
        /// <remarks/>
        public Status11Code Sts {
            get {
                return this.stsField;
            }
            set {
                this.stsField = value;
            }
        }
        
        /// <remarks/>
        public string AttndncCardNb {
            get {
                return this.attndncCardNbField;
            }
            set {
                this.attndncCardNbField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlInf {
            get {
                return this.addtlInfField;
            }
            set {
                this.addtlInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum Status11Code {
        
        /// <remarks/>
        PACK,
        
        /// <remarks/>
        ATTC,
        
        /// <remarks/>
        CAND,
        
        /// <remarks/>
        CSUB,
        
        /// <remarks/>
        FRWD,
        
        /// <remarks/>
        RCIS,
        
        /// <remarks/>
        REGM,
        
        /// <remarks/>
        STIN,
        
        /// <remarks/>
        DREG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class InstructionStatus13Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pdg", typeof(PendingStatus70Choice))]
        [System.Xml.Serialization.XmlElementAttribute("PrcgSts", typeof(InstructionProcessingStatus6))]
        [System.Xml.Serialization.XmlElementAttribute("Rjctd", typeof(RejectedStatus55Choice))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class DetailedInstructionStatus21 {
        
        private string snglInstrIdField;
        
        private string acctIdField;
        
        private string subAcctIdField;
        
        private InstructionStatus13Choice instrStsField;
        
        /// <remarks/>
        public string SnglInstrId {
            get {
                return this.snglInstrIdField;
            }
            set {
                this.snglInstrIdField = value;
            }
        }
        
        /// <remarks/>
        public string AcctId {
            get {
                return this.acctIdField;
            }
            set {
                this.acctIdField = value;
            }
        }
        
        /// <remarks/>
        public string SubAcctId {
            get {
                return this.subAcctIdField;
            }
            set {
                this.subAcctIdField = value;
            }
        }
        
        /// <remarks/>
        public InstructionStatus13Choice InstrSts {
            get {
                return this.instrStsField;
            }
            set {
                this.instrStsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class InstructionTypeStatus7Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CxlSts", typeof(CancellationStatus31Choice))]
        [System.Xml.Serialization.XmlElementAttribute("InstrSts", typeof(DetailedInstructionStatus21))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class IdentificationSource3Choice {
        
        private string itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class OtherIdentification1 {
        
        private string idField;
        
        private string sfxField;
        
        private IdentificationSource3Choice tpField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Sfx {
            get {
                return this.sfxField;
            }
            set {
                this.sfxField = value;
            }
        }
        
        /// <remarks/>
        public IdentificationSource3Choice Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class SecurityIdentification19 {
        
        private string iSINField;
        
        private OtherIdentification1[] othrIdField;
        
        private string descField;
        
        /// <remarks/>
        public string ISIN {
            get {
                return this.iSINField;
            }
            set {
                this.iSINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OthrId")]
        public OtherIdentification1[] OthrId {
            get {
                return this.othrIdField;
            }
            set {
                this.othrIdField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class NameAndAddress5 {
        
        private string nmField;
        
        private PostalAddress1 adrField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress1 Adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PostalAddress1 {
        
        private AddressType2Code adrTpField;
        
        private bool adrTpFieldSpecified;
        
        private string[] adrLineField;
        
        private string strtNmField;
        
        private string bldgNbField;
        
        private string pstCdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        /// <remarks/>
        public AddressType2Code AdrTp {
            get {
                return this.adrTpField;
            }
            set {
                this.adrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrTpSpecified {
            get {
                return this.adrTpFieldSpecified;
            }
            set {
                this.adrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string BldgNb {
            get {
                return this.bldgNbField;
            }
            set {
                this.bldgNbField = value;
            }
        }
        
        /// <remarks/>
        public string PstCd {
            get {
                return this.pstCdField;
            }
            set {
                this.pstCdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class PartyIdentification129Choice {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NmAndAdr", typeof(NameAndAddress5))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification36))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        AnyBIC,
        
        /// <remarks/>
        LEI,
        
        /// <remarks/>
        NmAndAdr,
        
        /// <remarks/>
        PrtryId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class GenericIdentification13 {
        
        private string idField;
        
        private string schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class MeetingTypeClassification2Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(MeetingTypeClassification2Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification13))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum MeetingTypeClassification2Code {
        
        /// <remarks/>
        AMET,
        
        /// <remarks/>
        CLAS,
        
        /// <remarks/>
        ISSU,
        
        /// <remarks/>
        OMET,
        
        /// <remarks/>
        VRHI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public partial class MeetingReference10 {
        
        private string mtgIdField;
        
        private string issrMtgIdField;
        
        private System.DateTime mtgDtAndTmField;
        
        private MeetingType4Code tpField;
        
        private MeetingTypeClassification2Choice clssfctnField;
        
        private PostalAddress1[] lctnField;
        
        private PartyIdentification129Choice issrField;
        
        /// <remarks/>
        public string MtgId {
            get {
                return this.mtgIdField;
            }
            set {
                this.mtgIdField = value;
            }
        }
        
        /// <remarks/>
        public string IssrMtgId {
            get {
                return this.issrMtgIdField;
            }
            set {
                this.issrMtgIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MtgDtAndTm {
            get {
                return this.mtgDtAndTmField;
            }
            set {
                this.mtgDtAndTmField = value;
            }
        }
        
        /// <remarks/>
        public MeetingType4Code Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public MeetingTypeClassification2Choice Clssfctn {
            get {
                return this.clssfctnField;
            }
            set {
                this.clssfctnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Lctn")]
        public PostalAddress1[] Lctn {
            get {
                return this.lctnField;
            }
            set {
                this.lctnField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification129Choice Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.006.001.11")]
    public enum MeetingType4Code {
        
        /// <remarks/>
        XMET,
        
        /// <remarks/>
        GMET,
        
        /// <remarks/>
        MIXD,
        
        /// <remarks/>
        SPCL,
        
        /// <remarks/>
        BMET,
        
        /// <remarks/>
        CMET,
    }
}
