//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ISO20022.Seev_003_001_10 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10", IsNullable=false)]
    public partial class Document {
        
        private MeetingEntitlementNotificationV10 mtgEntitlmntNtfctnField;
        
        /// <remarks/>
        public MeetingEntitlementNotificationV10 MtgEntitlmntNtfctn {
            get {
                return this.mtgEntitlmntNtfctnField;
            }
            set {
                this.mtgEntitlmntNtfctnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class MeetingEntitlementNotificationV10 {
        
        private NotificationType2Code ntfctnTpField;
        
        private string prvsEntitlmntNtfctnIdField;
        
        private MeetingReference10 mtgRefField;
        
        private PartyIdentification129Choice issrField;
        
        private SecurityPosition21[] sctyField;
        
        private EligibilityDates1 elgbltyField;
        
        private PartyIdentification232Choice mtgAttndeeField;
        
        private PartyIdentification232Choice prxyField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        public NotificationType2Code NtfctnTp {
            get {
                return this.ntfctnTpField;
            }
            set {
                this.ntfctnTpField = value;
            }
        }
        
        /// <remarks/>
        public string PrvsEntitlmntNtfctnId {
            get {
                return this.prvsEntitlmntNtfctnIdField;
            }
            set {
                this.prvsEntitlmntNtfctnIdField = value;
            }
        }
        
        /// <remarks/>
        public MeetingReference10 MtgRef {
            get {
                return this.mtgRefField;
            }
            set {
                this.mtgRefField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification129Choice Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Scty")]
        public SecurityPosition21[] Scty {
            get {
                return this.sctyField;
            }
            set {
                this.sctyField = value;
            }
        }
        
        /// <remarks/>
        public EligibilityDates1 Elgblty {
            get {
                return this.elgbltyField;
            }
            set {
                this.elgbltyField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification232Choice MtgAttndee {
            get {
                return this.mtgAttndeeField;
            }
            set {
                this.mtgAttndeeField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification232Choice Prxy {
            get {
                return this.prxyField;
            }
            set {
                this.prxyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum NotificationType2Code {
        
        /// <remarks/>
        NEWM,
        
        /// <remarks/>
        REPL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class MeetingReference10 {
        
        private string mtgIdField;
        
        private string issrMtgIdField;
        
        private System.DateTime mtgDtAndTmField;
        
        private MeetingType4Code tpField;
        
        private MeetingTypeClassification2Choice clssfctnField;
        
        private PostalAddress1[] lctnField;
        
        private PartyIdentification129Choice issrField;
        
        /// <remarks/>
        public string MtgId {
            get {
                return this.mtgIdField;
            }
            set {
                this.mtgIdField = value;
            }
        }
        
        /// <remarks/>
        public string IssrMtgId {
            get {
                return this.issrMtgIdField;
            }
            set {
                this.issrMtgIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime MtgDtAndTm {
            get {
                return this.mtgDtAndTmField;
            }
            set {
                this.mtgDtAndTmField = value;
            }
        }
        
        /// <remarks/>
        public MeetingType4Code Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public MeetingTypeClassification2Choice Clssfctn {
            get {
                return this.clssfctnField;
            }
            set {
                this.clssfctnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Lctn")]
        public PostalAddress1[] Lctn {
            get {
                return this.lctnField;
            }
            set {
                this.lctnField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification129Choice Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum MeetingType4Code {
        
        /// <remarks/>
        XMET,
        
        /// <remarks/>
        GMET,
        
        /// <remarks/>
        MIXD,
        
        /// <remarks/>
        SPCL,
        
        /// <remarks/>
        BMET,
        
        /// <remarks/>
        CMET,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class MeetingTypeClassification2Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(MeetingTypeClassification2Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification13))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum MeetingTypeClassification2Code {
        
        /// <remarks/>
        AMET,
        
        /// <remarks/>
        CLAS,
        
        /// <remarks/>
        ISSU,
        
        /// <remarks/>
        OMET,
        
        /// <remarks/>
        VRHI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class GenericIdentification13 {
        
        private string idField;
        
        private string schmeNmField;
        
        private string issrField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification232Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LglPrsn", typeof(PartyIdentification221))]
        [System.Xml.Serialization.XmlElementAttribute("NtrlPrsn", typeof(PartyIdentification238))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification221 {
        
        private PersonName2 nmAndAdrField;
        
        private string emailAdrField;
        
        private PartyIdentification198Choice idField;
        
        /// <remarks/>
        public PersonName2 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification198Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PersonName2 {
        
        private string nmField;
        
        private PostalAddress26 adrField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress26 Adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PostalAddress26 {
        
        private AddressType2Code adrTpField;
        
        private bool adrTpFieldSpecified;
        
        private string[] adrLineField;
        
        private string strtNmField;
        
        private string bldgNbField;
        
        private string pstBxField;
        
        private string pstCdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        /// <remarks/>
        public AddressType2Code AdrTp {
            get {
                return this.adrTpField;
            }
            set {
                this.adrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrTpSpecified {
            get {
                return this.adrTpFieldSpecified;
            }
            set {
                this.adrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string BldgNb {
            get {
                return this.bldgNbField;
            }
            set {
                this.bldgNbField = value;
            }
        }
        
        /// <remarks/>
        public string PstBx {
            get {
                return this.pstBxField;
            }
            set {
                this.pstBxField = value;
            }
        }
        
        /// <remarks/>
        public string PstCd {
            get {
                return this.pstCdField;
            }
            set {
                this.pstCdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum AddressType2Code {
        
        /// <remarks/>
        ADDR,
        
        /// <remarks/>
        PBOX,
        
        /// <remarks/>
        HOME,
        
        /// <remarks/>
        BIZZ,
        
        /// <remarks/>
        MLTO,
        
        /// <remarks/>
        DLVY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification198Choice {
        
        private object itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("ClntId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NtlRegnNb", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification36))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class GenericIdentification36 {
        
        private string idField;
        
        private string issrField;
        
        private string schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        AnyBIC,
        
        /// <remarks/>
        ClntId,
        
        /// <remarks/>
        LEI,
        
        /// <remarks/>
        NtlRegnNb,
        
        /// <remarks/>
        PrtryId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification238 {
        
        private PersonName3 nmAndAdrField;
        
        private string emailAdrField;
        
        private NaturalPersonIdentification1 idField;
        
        private string ntltyField;
        
        private DateAndPlaceOfBirth2 dtAndPlcOfBirthField;
        
        /// <remarks/>
        public PersonName3 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public NaturalPersonIdentification1 Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ntlty {
            get {
                return this.ntltyField;
            }
            set {
                this.ntltyField = value;
            }
        }
        
        /// <remarks/>
        public DateAndPlaceOfBirth2 DtAndPlcOfBirth {
            get {
                return this.dtAndPlcOfBirthField;
            }
            set {
                this.dtAndPlcOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PersonName3 {
        
        private NamePrefix2Code nmPrfxField;
        
        private bool nmPrfxFieldSpecified;
        
        private string frstNmField;
        
        private string srnmField;
        
        private PostalAddress26 adrField;
        
        /// <remarks/>
        public NamePrefix2Code NmPrfx {
            get {
                return this.nmPrfxField;
            }
            set {
                this.nmPrfxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NmPrfxSpecified {
            get {
                return this.nmPrfxFieldSpecified;
            }
            set {
                this.nmPrfxFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string FrstNm {
            get {
                return this.frstNmField;
            }
            set {
                this.frstNmField = value;
            }
        }
        
        /// <remarks/>
        public string Srnm {
            get {
                return this.srnmField;
            }
            set {
                this.srnmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress26 Adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum NamePrefix2Code {
        
        /// <remarks/>
        DOCT,
        
        /// <remarks/>
        MADM,
        
        /// <remarks/>
        MISS,
        
        /// <remarks/>
        MIST,
        
        /// <remarks/>
        MIKS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class NaturalPersonIdentification1 {
        
        private string idField;
        
        private IdentificationType45Choice idTpField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public IdentificationType45Choice IdTp {
            get {
                return this.idTpField;
            }
            set {
                this.idTpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class IdentificationType45Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(TypeOfIdentification4Code))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification30))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum TypeOfIdentification4Code {
        
        /// <remarks/>
        ARNU,
        
        /// <remarks/>
        CUST,
        
        /// <remarks/>
        CORP,
        
        /// <remarks/>
        DRLC,
        
        /// <remarks/>
        IDCD,
        
        /// <remarks/>
        NRIN,
        
        /// <remarks/>
        CCPT,
        
        /// <remarks/>
        SOCS,
        
        /// <remarks/>
        TXID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class GenericIdentification30 {
        
        private string idField;
        
        private string issrField;
        
        private string schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class DateAndPlaceOfBirth2 {
        
        private System.DateTime birthDtField;
        
        private string prvcOfBirthField;
        
        private string cityOfBirthField;
        
        private string ctryOfBirthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime BirthDt {
            get {
                return this.birthDtField;
            }
            set {
                this.birthDtField = value;
            }
        }
        
        /// <remarks/>
        public string PrvcOfBirth {
            get {
                return this.prvcOfBirthField;
            }
            set {
                this.prvcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CityOfBirth {
            get {
                return this.cityOfBirthField;
            }
            set {
                this.cityOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfBirth {
            get {
                return this.ctryOfBirthField;
            }
            set {
                this.ctryOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class EligibilityDates1 {
        
        private System.DateTime entitlmntFxgDtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime EntitlmntFxgDt {
            get {
                return this.entitlmntFxgDtField;
            }
            set {
                this.entitlmntFxgDtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification250 {
        
        private PersonName3 nmAndAdrField;
        
        private string emailAdrField;
        
        private NaturalPersonIdentification1 idField;
        
        private string ntltyField;
        
        private DateAndPlaceOfBirth2 dtAndPlcOfBirthField;
        
        private string cpnyRegrShrhldrIdField;
        
        /// <remarks/>
        public PersonName3 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public NaturalPersonIdentification1 Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Ntlty {
            get {
                return this.ntltyField;
            }
            set {
                this.ntltyField = value;
            }
        }
        
        /// <remarks/>
        public DateAndPlaceOfBirth2 DtAndPlcOfBirth {
            get {
                return this.dtAndPlcOfBirthField;
            }
            set {
                this.dtAndPlcOfBirthField = value;
            }
        }
        
        /// <remarks/>
        public string CpnyRegrShrhldrId {
            get {
                return this.cpnyRegrShrhldrIdField;
            }
            set {
                this.cpnyRegrShrhldrIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification269 {
        
        private PersonName2 nmAndAdrField;
        
        private string emailAdrField;
        
        private PartyIdentification198Choice idField;
        
        private string cpnyRegrShrhldrIdField;
        
        private string ctryOfIncorprtnField;
        
        /// <remarks/>
        public PersonName2 NmAndAdr {
            get {
                return this.nmAndAdrField;
            }
            set {
                this.nmAndAdrField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAdr {
            get {
                return this.emailAdrField;
            }
            set {
                this.emailAdrField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification198Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string CpnyRegrShrhldrId {
            get {
                return this.cpnyRegrShrhldrIdField;
            }
            set {
                this.cpnyRegrShrhldrIdField = value;
            }
        }
        
        /// <remarks/>
        public string CtryOfIncorprtn {
            get {
                return this.ctryOfIncorprtnField;
            }
            set {
                this.ctryOfIncorprtnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification246Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LglPrsn", typeof(PartyIdentification269))]
        [System.Xml.Serialization.XmlElementAttribute("NtrlPrsn", typeof(PartyIdentification250))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification270 {
        
        private PartyIdentification246Choice idField;
        
        private PartyAdditionalIdentification2Choice addtlIdInfField;
        
        /// <remarks/>
        public PartyIdentification246Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PartyAdditionalIdentification2Choice AddtlIdInf {
            get {
                return this.addtlIdInfField;
            }
            set {
                this.addtlIdInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyAdditionalIdentification2Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BirthDt", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("RegnId", typeof(OrganisationIdentification5))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class OrganisationIdentification5 {
        
        private string regnNbField;
        
        private string regrNmField;
        
        /// <remarks/>
        public string RegnNb {
            get {
                return this.regnNbField;
            }
            set {
                this.regnNbField = value;
            }
        }
        
        /// <remarks/>
        public string RegrNm {
            get {
                return this.regrNmField;
            }
            set {
                this.regrNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class GenericIdentification78 {
        
        private GenericIdentification30 tpField;
        
        private string idField;
        
        /// <remarks/>
        public GenericIdentification30 Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class SafekeepingPlaceTypeAndIdentification1 {
        
        private SafekeepingPlace1Code sfkpgPlcTpField;
        
        private string idField;
        
        /// <remarks/>
        public SafekeepingPlace1Code SfkpgPlcTp {
            get {
                return this.sfkpgPlcTpField;
            }
            set {
                this.sfkpgPlcTpField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum SafekeepingPlace1Code {
        
        /// <remarks/>
        CUST,
        
        /// <remarks/>
        ICSD,
        
        /// <remarks/>
        NCSD,
        
        /// <remarks/>
        SHHE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class SafekeepingPlaceTypeAndText6 {
        
        private SafekeepingPlace2Code sfkpgPlcTpField;
        
        private string idField;
        
        /// <remarks/>
        public SafekeepingPlace2Code SfkpgPlcTp {
            get {
                return this.sfkpgPlcTpField;
            }
            set {
                this.sfkpgPlcTpField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum SafekeepingPlace2Code {
        
        /// <remarks/>
        SHHE,
        
        /// <remarks/>
        ALLP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class SafekeepingPlaceFormat42Choice {
        
        private object itemField;
        
        private ItemChoiceType4 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ctry", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("DgtlLdgrId", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Id", typeof(SafekeepingPlaceTypeAndText6))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification78))]
        [System.Xml.Serialization.XmlElementAttribute("TpAndId", typeof(SafekeepingPlaceTypeAndIdentification1))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType4 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10", IncludeInSchema=false)]
    public enum ItemChoiceType4 {
        
        /// <remarks/>
        Ctry,
        
        /// <remarks/>
        DgtlLdgrId,
        
        /// <remarks/>
        Id,
        
        /// <remarks/>
        Prtry,
        
        /// <remarks/>
        TpAndId,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class FinancialInstrumentQuantity45Choice {
        
        private decimal itemField;
        
        private ItemChoiceType3 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DgtlTknUnit", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("FaceAmt", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("Unit", typeof(decimal))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public decimal Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType3 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10", IncludeInSchema=false)]
    public enum ItemChoiceType3 {
        
        /// <remarks/>
        DgtlTknUnit,
        
        /// <remarks/>
        FaceAmt,
        
        /// <remarks/>
        Unit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class SignedQuantityFormat14 {
        
        private ShortLong1Code shrtLngPosField;
        
        private FinancialInstrumentQuantity45Choice qtyField;
        
        /// <remarks/>
        public ShortLong1Code ShrtLngPos {
            get {
                return this.shrtLngPosField;
            }
            set {
                this.shrtLngPosField = value;
            }
        }
        
        /// <remarks/>
        public FinancialInstrumentQuantity45Choice Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum ShortLong1Code {
        
        /// <remarks/>
        SHOR,
        
        /// <remarks/>
        LONG,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class HoldingBalance14 {
        
        private SignedQuantityFormat14 balField;
        
        private SecuritiesEntryType2Code balTpField;
        
        private SafekeepingPlaceFormat42Choice sfkpgPlcField;
        
        private System.DateTime dtField;
        
        private bool dtFieldSpecified;
        
        /// <remarks/>
        public SignedQuantityFormat14 Bal {
            get {
                return this.balField;
            }
            set {
                this.balField = value;
            }
        }
        
        /// <remarks/>
        public SecuritiesEntryType2Code BalTp {
            get {
                return this.balTpField;
            }
            set {
                this.balTpField = value;
            }
        }
        
        /// <remarks/>
        public SafekeepingPlaceFormat42Choice SfkpgPlc {
            get {
                return this.sfkpgPlcField;
            }
            set {
                this.sfkpgPlcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Dt {
            get {
                return this.dtField;
            }
            set {
                this.dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DtSpecified {
            get {
                return this.dtFieldSpecified;
            }
            set {
                this.dtFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public enum SecuritiesEntryType2Code {
        
        /// <remarks/>
        BLOK,
        
        /// <remarks/>
        ELIG,
        
        /// <remarks/>
        PEND,
        
        /// <remarks/>
        PENR,
        
        /// <remarks/>
        NOMI,
        
        /// <remarks/>
        SETD,
        
        /// <remarks/>
        BORR,
        
        /// <remarks/>
        LOAN,
        
        /// <remarks/>
        SPOS,
        
        /// <remarks/>
        TRAD,
        
        /// <remarks/>
        COLI,
        
        /// <remarks/>
        COLO,
        
        /// <remarks/>
        UNBA,
        
        /// <remarks/>
        INBA,
        
        /// <remarks/>
        REGO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification231Choice {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LglPrsn", typeof(PartyIdentification221))]
        [System.Xml.Serialization.XmlElementAttribute("NtrlPrsn", typeof(PartyIdentification238))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification241 {
        
        private PartyIdentification231Choice idField;
        
        private PartyAdditionalIdentification2Choice addtlIdInfField;
        
        /// <remarks/>
        public PartyIdentification231Choice Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PartyAdditionalIdentification2Choice AddtlIdInf {
            get {
                return this.addtlIdInfField;
            }
            set {
                this.addtlIdInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class EligiblePosition19 {
        
        private string acctIdField;
        
        private string blckChainAdrOrWlltField;
        
        private PartyIdentification241 acctOwnrField;
        
        private HoldingBalance14[] hldgBalField;
        
        private PartyIdentification270[] rghtsHldrField;
        
        /// <remarks/>
        public string AcctId {
            get {
                return this.acctIdField;
            }
            set {
                this.acctIdField = value;
            }
        }
        
        /// <remarks/>
        public string BlckChainAdrOrWllt {
            get {
                return this.blckChainAdrOrWlltField;
            }
            set {
                this.blckChainAdrOrWlltField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification241 AcctOwnr {
            get {
                return this.acctOwnrField;
            }
            set {
                this.acctOwnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HldgBal")]
        public HoldingBalance14[] HldgBal {
            get {
                return this.hldgBalField;
            }
            set {
                this.hldgBalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RghtsHldr")]
        public PartyIdentification270[] RghtsHldr {
            get {
                return this.rghtsHldrField;
            }
            set {
                this.rghtsHldrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class IdentificationSource3Choice {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cd", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        Cd,
        
        /// <remarks/>
        Prtry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class OtherIdentification1 {
        
        private string idField;
        
        private string sfxField;
        
        private IdentificationSource3Choice tpField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Sfx {
            get {
                return this.sfxField;
            }
            set {
                this.sfxField = value;
            }
        }
        
        /// <remarks/>
        public IdentificationSource3Choice Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class SecurityIdentification19 {
        
        private string iSINField;
        
        private OtherIdentification1[] othrIdField;
        
        private string descField;
        
        /// <remarks/>
        public string ISIN {
            get {
                return this.iSINField;
            }
            set {
                this.iSINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OthrId")]
        public OtherIdentification1[] OthrId {
            get {
                return this.othrIdField;
            }
            set {
                this.othrIdField = value;
            }
        }
        
        /// <remarks/>
        public string Desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class SecurityPosition21 {
        
        private SecurityIdentification19 finInstrmIdField;
        
        private EligiblePosition19[] posField;
        
        /// <remarks/>
        public SecurityIdentification19 FinInstrmId {
            get {
                return this.finInstrmIdField;
            }
            set {
                this.finInstrmIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pos")]
        public EligiblePosition19[] Pos {
            get {
                return this.posField;
            }
            set {
                this.posField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class NameAndAddress5 {
        
        private string nmField;
        
        private PostalAddress1 adrField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress1 Adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PostalAddress1 {
        
        private AddressType2Code adrTpField;
        
        private bool adrTpFieldSpecified;
        
        private string[] adrLineField;
        
        private string strtNmField;
        
        private string bldgNbField;
        
        private string pstCdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        /// <remarks/>
        public AddressType2Code AdrTp {
            get {
                return this.adrTpField;
            }
            set {
                this.adrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdrTpSpecified {
            get {
                return this.adrTpFieldSpecified;
            }
            set {
                this.adrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdrLine")]
        public string[] AdrLine {
            get {
                return this.adrLineField;
            }
            set {
                this.adrLineField = value;
            }
        }
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string BldgNb {
            get {
                return this.bldgNbField;
            }
            set {
                this.bldgNbField = value;
            }
        }
        
        /// <remarks/>
        public string PstCd {
            get {
                return this.pstCdField;
            }
            set {
                this.pstCdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10")]
    public partial class PartyIdentification129Choice {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("LEI", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NmAndAdr", typeof(NameAndAddress5))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification36))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:seev.003.001.10", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        AnyBIC,
        
        /// <remarks/>
        LEI,
        
        /// <remarks/>
        NmAndAdr,
        
        /// <remarks/>
        PrtryId,
    }
}
