//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ISO20022.Fxtr_033_001_02 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:fxtr.033.001.02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:fxtr.033.001.02", IsNullable=false)]
    public partial class Document {
        
        private ForeignExchangeTradeCaptureReportAcknowledgementV02 fXTradCaptrRptAckField;
        
        /// <remarks/>
        public ForeignExchangeTradeCaptureReportAcknowledgementV02 FXTradCaptrRptAck {
            get {
                return this.fXTradCaptrRptAckField;
            }
            set {
                this.fXTradCaptrRptAckField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:fxtr.033.001.02")]
    public partial class ForeignExchangeTradeCaptureReportAcknowledgementV02 {
        
        private MessageIdentification1 ackIdField;
        
        private string tradIdField;
        
        private string dealTcktIdField;
        
        private Status5Code stsField;
        
        private AdditionalReferences2 refField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        public MessageIdentification1 AckId {
            get {
                return this.ackIdField;
            }
            set {
                this.ackIdField = value;
            }
        }
        
        /// <remarks/>
        public string TradId {
            get {
                return this.tradIdField;
            }
            set {
                this.tradIdField = value;
            }
        }
        
        /// <remarks/>
        public string DealTcktId {
            get {
                return this.dealTcktIdField;
            }
            set {
                this.dealTcktIdField = value;
            }
        }
        
        /// <remarks/>
        public Status5Code Sts {
            get {
                return this.stsField;
            }
            set {
                this.stsField = value;
            }
        }
        
        /// <remarks/>
        public AdditionalReferences2 Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:fxtr.033.001.02")]
    public partial class MessageIdentification1 {
        
        private string idField;
        
        private System.DateTime creDtTmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtTm {
            get {
                return this.creDtTmField;
            }
            set {
                this.creDtTmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:fxtr.033.001.02")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:fxtr.033.001.02")]
    public partial class AdditionalReferences2 {
        
        private string refField;
        
        private string msgNmField;
        
        private string refIssrField;
        
        /// <remarks/>
        public string Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        public string MsgNm {
            get {
                return this.msgNmField;
            }
            set {
                this.msgNmField = value;
            }
        }
        
        /// <remarks/>
        public string RefIssr {
            get {
                return this.refIssrField;
            }
            set {
                this.refIssrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:fxtr.033.001.02")]
    public enum Status5Code {
        
        /// <remarks/>
        REJT,
        
        /// <remarks/>
        PACK,
        
        /// <remarks/>
        PDNG,
    }
}
