//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ISO20022.Colr_006_001_05 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05", IsNullable=false)]
    public partial class Document {
        
        private CollateralManagementCancellationStatusV05 collMgmtCxlStsField;
        
        /// <remarks/>
        public CollateralManagementCancellationStatusV05 CollMgmtCxlSts {
            get {
                return this.collMgmtCxlStsField;
            }
            set {
                this.collMgmtCxlStsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class CollateralManagementCancellationStatusV05 {
        
        private string txIdField;
        
        private Reference16 refField;
        
        private Obligation9 oblgtnField;
        
        private CollateralCancellationStatus2 cxlStsField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        public string TxId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
            }
        }
        
        /// <remarks/>
        public Reference16 Ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        public Obligation9 Oblgtn {
            get {
                return this.oblgtnField;
            }
            set {
                this.oblgtnField = value;
            }
        }
        
        /// <remarks/>
        public CollateralCancellationStatus2 CxlSts {
            get {
                return this.cxlStsField;
            }
            set {
                this.cxlStsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class Reference16 {
        
        private string collMsgCxlReqIdField;
        
        /// <remarks/>
        public string CollMsgCxlReqId {
            get {
                return this.collMsgCxlReqIdField;
            }
            set {
                this.collMsgCxlReqIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class RejectionStatus3 {
        
        private RejectionReason68Code rjctdRsnField;
        
        private string addtlInfField;
        
        /// <remarks/>
        public RejectionReason68Code RjctdRsn {
            get {
                return this.rjctdRsnField;
            }
            set {
                this.rjctdRsnField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlInf {
            get {
                return this.addtlInfField;
            }
            set {
                this.addtlInfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public enum RejectionReason68Code {
        
        /// <remarks/>
        DSEC,
        
        /// <remarks/>
        EVNM,
        
        /// <remarks/>
        UKWN,
        
        /// <remarks/>
        ICOL,
        
        /// <remarks/>
        CONL,
        
        /// <remarks/>
        ELIG,
        
        /// <remarks/>
        INID,
        
        /// <remarks/>
        OTHR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class CollateralCancellationStatus2 {
        
        private Status4Code collStsCdField;
        
        private string addtlInfField;
        
        private RejectionStatus3 rjctnDtlsField;
        
        /// <remarks/>
        public Status4Code CollStsCd {
            get {
                return this.collStsCdField;
            }
            set {
                this.collStsCdField = value;
            }
        }
        
        /// <remarks/>
        public string AddtlInf {
            get {
                return this.addtlInfField;
            }
            set {
                this.addtlInfField = value;
            }
        }
        
        /// <remarks/>
        public RejectionStatus3 RjctnDtls {
            get {
                return this.rjctnDtlsField;
            }
            set {
                this.rjctnDtlsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public enum Status4Code {
        
        /// <remarks/>
        REJT,
        
        /// <remarks/>
        PACK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class DateAndDateTime2Choice {
        
        private System.DateTime itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Dt", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("DtTm", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public System.DateTime Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        Dt,
        
        /// <remarks/>
        DtTm,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class BlockChainAddressWallet5 {
        
        private string idField;
        
        private CollateralAccountIdentificationType3Choice tpField;
        
        private string nmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public CollateralAccountIdentificationType3Choice Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class CollateralAccountIdentificationType3Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Prtry", typeof(GenericIdentification36))]
        [System.Xml.Serialization.XmlElementAttribute("Tp", typeof(CollateralAccountType1Code))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class GenericIdentification36 {
        
        private string idField;
        
        private string issrField;
        
        private string schmeNmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Issr {
            get {
                return this.issrField;
            }
            set {
                this.issrField = value;
            }
        }
        
        /// <remarks/>
        public string SchmeNm {
            get {
                return this.schmeNmField;
            }
            set {
                this.schmeNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public enum CollateralAccountType1Code {
        
        /// <remarks/>
        HOUS,
        
        /// <remarks/>
        CLIE,
        
        /// <remarks/>
        LIPR,
        
        /// <remarks/>
        MGIN,
        
        /// <remarks/>
        DFLT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class CollateralAccount3 {
        
        private string idField;
        
        private CollateralAccountIdentificationType3Choice tpField;
        
        private string nmField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public CollateralAccountIdentificationType3Choice Tp {
            get {
                return this.tpField;
            }
            set {
                this.tpField = value;
            }
        }
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class PostalAddress2 {
        
        private string strtNmField;
        
        private string pstCdIdField;
        
        private string twnNmField;
        
        private string ctrySubDvsnField;
        
        private string ctryField;
        
        /// <remarks/>
        public string StrtNm {
            get {
                return this.strtNmField;
            }
            set {
                this.strtNmField = value;
            }
        }
        
        /// <remarks/>
        public string PstCdId {
            get {
                return this.pstCdIdField;
            }
            set {
                this.pstCdIdField = value;
            }
        }
        
        /// <remarks/>
        public string TwnNm {
            get {
                return this.twnNmField;
            }
            set {
                this.twnNmField = value;
            }
        }
        
        /// <remarks/>
        public string CtrySubDvsn {
            get {
                return this.ctrySubDvsnField;
            }
            set {
                this.ctrySubDvsnField = value;
            }
        }
        
        /// <remarks/>
        public string Ctry {
            get {
                return this.ctryField;
            }
            set {
                this.ctryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class NameAndAddress6 {
        
        private string nmField;
        
        private PostalAddress2 adrField;
        
        /// <remarks/>
        public string Nm {
            get {
                return this.nmField;
            }
            set {
                this.nmField = value;
            }
        }
        
        /// <remarks/>
        public PostalAddress2 Adr {
            get {
                return this.adrField;
            }
            set {
                this.adrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class PartyIdentification178Choice {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AnyBIC", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NmAndAdr", typeof(NameAndAddress6))]
        [System.Xml.Serialization.XmlElementAttribute("PrtryId", typeof(GenericIdentification36))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public partial class Obligation9 {
        
        private PartyIdentification178Choice ptyAField;
        
        private PartyIdentification178Choice svcgPtyAField;
        
        private PartyIdentification178Choice ptyBField;
        
        private PartyIdentification178Choice svcgPtyBField;
        
        private CollateralAccount3 collAcctIdField;
        
        private BlockChainAddressWallet5 blckChainAdrOrWlltField;
        
        private ExposureType11Code xpsrTpField;
        
        private bool xpsrTpFieldSpecified;
        
        private DateAndDateTime2Choice valtnDtField;
        
        /// <remarks/>
        public PartyIdentification178Choice PtyA {
            get {
                return this.ptyAField;
            }
            set {
                this.ptyAField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification178Choice SvcgPtyA {
            get {
                return this.svcgPtyAField;
            }
            set {
                this.svcgPtyAField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification178Choice PtyB {
            get {
                return this.ptyBField;
            }
            set {
                this.ptyBField = value;
            }
        }
        
        /// <remarks/>
        public PartyIdentification178Choice SvcgPtyB {
            get {
                return this.svcgPtyBField;
            }
            set {
                this.svcgPtyBField = value;
            }
        }
        
        /// <remarks/>
        public CollateralAccount3 CollAcctId {
            get {
                return this.collAcctIdField;
            }
            set {
                this.collAcctIdField = value;
            }
        }
        
        /// <remarks/>
        public BlockChainAddressWallet5 BlckChainAdrOrWllt {
            get {
                return this.blckChainAdrOrWlltField;
            }
            set {
                this.blckChainAdrOrWlltField = value;
            }
        }
        
        /// <remarks/>
        public ExposureType11Code XpsrTp {
            get {
                return this.xpsrTpField;
            }
            set {
                this.xpsrTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XpsrTpSpecified {
            get {
                return this.xpsrTpFieldSpecified;
            }
            set {
                this.xpsrTpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DateAndDateTime2Choice ValtnDt {
            get {
                return this.valtnDtField;
            }
            set {
                this.valtnDtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:colr.006.001.05")]
    public enum ExposureType11Code {
        
        /// <remarks/>
        BFWD,
        
        /// <remarks/>
        PAYM,
        
        /// <remarks/>
        CBCO,
        
        /// <remarks/>
        COMM,
        
        /// <remarks/>
        CRDS,
        
        /// <remarks/>
        CRTL,
        
        /// <remarks/>
        CRSP,
        
        /// <remarks/>
        CCIR,
        
        /// <remarks/>
        CRPR,
        
        /// <remarks/>
        EQPT,
        
        /// <remarks/>
        EQUS,
        
        /// <remarks/>
        EXTD,
        
        /// <remarks/>
        EXPT,
        
        /// <remarks/>
        FIXI,
        
        /// <remarks/>
        FORX,
        
        /// <remarks/>
        FORW,
        
        /// <remarks/>
        FUTR,
        
        /// <remarks/>
        OPTN,
        
        /// <remarks/>
        LIQU,
        
        /// <remarks/>
        OTCD,
        
        /// <remarks/>
        RVPO,
        
        /// <remarks/>
        SLOA,
        
        /// <remarks/>
        SBSC,
        
        /// <remarks/>
        SCRP,
        
        /// <remarks/>
        SLEB,
        
        /// <remarks/>
        SCIR,
        
        /// <remarks/>
        SCIE,
        
        /// <remarks/>
        SWPT,
        
        /// <remarks/>
        TBAS,
        
        /// <remarks/>
        TRCP,
        
        /// <remarks/>
        UDMS,
        
        /// <remarks/>
        CCPC,
        
        /// <remarks/>
        EQUI,
        
        /// <remarks/>
        TRBD,
        
        /// <remarks/>
        REPO,
        
        /// <remarks/>
        SHSL,
    }
}
