using Microsoft.VisualStudio.TestTools.UnitTesting;
using Wolff.FinanceTools.Base;
using Wolff.FinanceTools.UK;

namespace ISO20022.Tests.Wolff
{
    [TestClass]
    public class CalcIbanTests
    {
        [TestMethod]
        public void CalculateIban_UK_Test_Success()
        {
            // input:        60-16-13 31926819
            // output local: NWBK60161331926819
            // output iban:  GB29NWBK60161331926819
            UkAccntNumberToIban ukAccntNumberToIban = new UkAccntNumberToIban();

            var iban = ukAccntNumberToIban.Convert("NWBK", "601613", "31926819");

            Assert.AreEqual("GB29NWBK60161331926819", iban);
        }

        [TestMethod]
        public void CalculateCheckDigits_BE_Test_Success()
        {
            // 510007547061BE00 is our calculation example
            CalculationBase calculationBase = new CalculationBase();

            Assert.AreEqual("62", calculationBase.GenerateCheckDigitsFromBban("510007547061BE00"));
        }

        [TestMethod]
        public void CalculateCheckDigits_CH_Test_Success()
        {
            // 0027427412018940ECH00 is our calculation example
            CalculationBase calculationBase = new CalculationBase();

            Assert.AreEqual("86", calculationBase.GenerateCheckDigitsFromBban("0027427412018940ECH00"));
        }

        [TestMethod]
        public void CalculateCheckDigits_Test_Success()
        {
            UkAccntNumberToIban ukAccntNumberToIban = new UkAccntNumberToIban();
            IbanNet.Registry.IbanGenerator generator = new IbanNet.Registry.IbanGenerator();

            // verify that the check digits generated by our method match those generated by the IbanNet library for a large number of random UK IBANs
            for (int i = 0; i < 10000; i++)
            {
                var iban = generator.Generate("GB");
                var checkDigits = ukAccntNumberToIban.GenerateCheckDigitsFromBban(iban.Bban + "GB00");
                Assert.AreEqual(iban.ToString().Substring(2, 2), checkDigits);
            }
        }
    }
}