//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ISO20022.Auth_060_001_02 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02", IsNullable=false)]
    public partial class Document {
        
        private CCPDailyCashFlowsReportV02 cCPDalyCshFlowsRptField;
        
        /// <remarks/>
        public CCPDailyCashFlowsReportV02 CCPDalyCshFlowsRpt {
            get {
                return this.cCPDalyCshFlowsRptField;
            }
            set {
                this.cCPDalyCshFlowsRptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class CCPDailyCashFlowsReportV02 {
        
        private ConcentrationAgent1[] cncntrtnAgtField;
        
        private SettlementAgent2[] sttlmAgtField;
        
        private SupplementaryData1[] splmtryDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CncntrtnAgt")]
        public ConcentrationAgent1[] CncntrtnAgt {
            get {
                return this.cncntrtnAgtField;
            }
            set {
                this.cncntrtnAgtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SttlmAgt")]
        public SettlementAgent2[] SttlmAgt {
            get {
                return this.sttlmAgtField;
            }
            set {
                this.sttlmAgtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SplmtryData")]
        public SupplementaryData1[] SplmtryData {
            get {
                return this.splmtryDataField;
            }
            set {
                this.splmtryDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class ConcentrationAgent1 {
        
        private string idField;
        
        private ConcentrationAccount1[] acctField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Acct")]
        public ConcentrationAccount1[] Acct {
            get {
                return this.acctField;
            }
            set {
                this.acctField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class ConcentrationAccount1 {
        
        private Flows1 inFlowField;
        
        private Flows1 outFlowField;
        
        private AmountAndDirection102 endOfDayField;
        
        private ActiveCurrencyAndAmount peakCdtField;
        
        private ActiveCurrencyAndAmount peakDbtField;
        
        private string latePmtConfField;
        
        /// <remarks/>
        public Flows1 InFlow {
            get {
                return this.inFlowField;
            }
            set {
                this.inFlowField = value;
            }
        }
        
        /// <remarks/>
        public Flows1 OutFlow {
            get {
                return this.outFlowField;
            }
            set {
                this.outFlowField = value;
            }
        }
        
        /// <remarks/>
        public AmountAndDirection102 EndOfDay {
            get {
                return this.endOfDayField;
            }
            set {
                this.endOfDayField = value;
            }
        }
        
        /// <remarks/>
        public ActiveCurrencyAndAmount PeakCdt {
            get {
                return this.peakCdtField;
            }
            set {
                this.peakCdtField = value;
            }
        }
        
        /// <remarks/>
        public ActiveCurrencyAndAmount PeakDbt {
            get {
                return this.peakDbtField;
            }
            set {
                this.peakDbtField = value;
            }
        }
        
        /// <remarks/>
        public string LatePmtConf {
            get {
                return this.latePmtConfField;
            }
            set {
                this.latePmtConfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class Flows1 {
        
        private AmountAndDirection102 pmtBkFlowsField;
        
        private AmountAndDirection102 invstmtFlowsField;
        
        /// <remarks/>
        public AmountAndDirection102 PmtBkFlows {
            get {
                return this.pmtBkFlowsField;
            }
            set {
                this.pmtBkFlowsField = value;
            }
        }
        
        /// <remarks/>
        public AmountAndDirection102 InvstmtFlows {
            get {
                return this.invstmtFlowsField;
            }
            set {
                this.invstmtFlowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class AmountAndDirection102 {
        
        private ActiveCurrencyAndAmount amtField;
        
        private bool sgnField;
        
        /// <remarks/>
        public ActiveCurrencyAndAmount Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public bool Sgn {
            get {
                return this.sgnField;
            }
            set {
                this.sgnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class ActiveCurrencyAndAmount {
        
        private string ccyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class SupplementaryData1 {
        
        private string plcAndNmField;
        
        private System.Xml.XmlElement envlpField;
        
        /// <remarks/>
        public string PlcAndNm {
            get {
                return this.plcAndNmField;
            }
            set {
                this.plcAndNmField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Envlp {
            get {
                return this.envlpField;
            }
            set {
                this.envlpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class AmountAndDirection86 {
        
        private decimal amtField;
        
        private bool sgnField;
        
        /// <remarks/>
        public decimal Amt {
            get {
                return this.amtField;
            }
            set {
                this.amtField = value;
            }
        }
        
        /// <remarks/>
        public bool Sgn {
            get {
                return this.sgnField;
            }
            set {
                this.sgnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class PaymentAccount4 {
        
        private string ccyField;
        
        private AmountAndDirection86 netPmtField;
        
        private decimal grssCdtsField;
        
        private decimal grssDbtsField;
        
        private string latePmtConfField;
        
        /// <remarks/>
        public string Ccy {
            get {
                return this.ccyField;
            }
            set {
                this.ccyField = value;
            }
        }
        
        /// <remarks/>
        public AmountAndDirection86 NetPmt {
            get {
                return this.netPmtField;
            }
            set {
                this.netPmtField = value;
            }
        }
        
        /// <remarks/>
        public decimal GrssCdts {
            get {
                return this.grssCdtsField;
            }
            set {
                this.grssCdtsField = value;
            }
        }
        
        /// <remarks/>
        public decimal GrssDbts {
            get {
                return this.grssDbtsField;
            }
            set {
                this.grssDbtsField = value;
            }
        }
        
        /// <remarks/>
        public string LatePmtConf {
            get {
                return this.latePmtConfField;
            }
            set {
                this.latePmtConfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:auth.060.001.02")]
    public partial class SettlementAgent2 {
        
        private string idField;
        
        private PaymentAccount4[] acctField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Acct")]
        public PaymentAccount4[] Acct {
            get {
                return this.acctField;
            }
            set {
                this.acctField = value;
            }
        }
    }
}
