//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.9037.0.
// 
namespace ISO20022.Head_002_001_01 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:head.002.001.01")]
    [System.Xml.Serialization.XmlRootAttribute("Xchg", Namespace="urn:iso:std:iso:20022:tech:xsd:head.002.001.01", IsNullable=false)]
    public partial class BusinessFileHeaderV01 {
        
        private PayloadDescription2 pyldDescField;
        
        private System.Xml.XmlElement[] pyldField;
        
        /// <remarks/>
        public PayloadDescription2 PyldDesc {
            get {
                return this.pyldDescField;
            }
            set {
                this.pyldDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Pyld")]
        public System.Xml.XmlElement[] Pyld {
            get {
                return this.pyldField;
            }
            set {
                this.pyldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:head.002.001.01")]
    public partial class PayloadDescription2 {
        
        private PayloadData2 pyldDataField;
        
        private ApplicationSpecifics1 applSpcfcsField;
        
        private string pyldTpField;
        
        private ManifestData2[] mnfstDataField;
        
        /// <remarks/>
        public PayloadData2 PyldData {
            get {
                return this.pyldDataField;
            }
            set {
                this.pyldDataField = value;
            }
        }
        
        /// <remarks/>
        public ApplicationSpecifics1 ApplSpcfcs {
            get {
                return this.applSpcfcsField;
            }
            set {
                this.applSpcfcsField = value;
            }
        }
        
        /// <remarks/>
        public string PyldTp {
            get {
                return this.pyldTpField;
            }
            set {
                this.pyldTpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MnfstData")]
        public ManifestData2[] MnfstData {
            get {
                return this.mnfstDataField;
            }
            set {
                this.mnfstDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:head.002.001.01")]
    public partial class PayloadData2 {
        
        private string pyldIdrField;
        
        private System.DateTime creDtAndTmField;
        
        private bool pssblDplctFlgField;
        
        private bool pssblDplctFlgFieldSpecified;
        
        /// <remarks/>
        public string PyldIdr {
            get {
                return this.pyldIdrField;
            }
            set {
                this.pyldIdrField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreDtAndTm {
            get {
                return this.creDtAndTmField;
            }
            set {
                this.creDtAndTmField = value;
            }
        }
        
        /// <remarks/>
        public bool PssblDplctFlg {
            get {
                return this.pssblDplctFlgField;
            }
            set {
                this.pssblDplctFlgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PssblDplctFlgSpecified {
            get {
                return this.pssblDplctFlgFieldSpecified;
            }
            set {
                this.pssblDplctFlgFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:head.002.001.01")]
    public partial class ManifestData2 {
        
        private string docTpField;
        
        private decimal nbOfDocsField;
        
        /// <remarks/>
        public string DocTp {
            get {
                return this.docTpField;
            }
            set {
                this.docTpField = value;
            }
        }
        
        /// <remarks/>
        public decimal NbOfDocs {
            get {
                return this.nbOfDocsField;
            }
            set {
                this.nbOfDocsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:iso:std:iso:20022:tech:xsd:head.002.001.01")]
    public partial class ApplicationSpecifics1 {
        
        private string sysUsrField;
        
        private System.Xml.XmlElement sgntrField;
        
        private decimal ttlNbOfDocsField;
        
        /// <remarks/>
        public string SysUsr {
            get {
                return this.sysUsrField;
            }
            set {
                this.sysUsrField = value;
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Sgntr {
            get {
                return this.sgntrField;
            }
            set {
                this.sgntrField = value;
            }
        }
        
        /// <remarks/>
        public decimal TtlNbOfDocs {
            get {
                return this.ttlNbOfDocsField;
            }
            set {
                this.ttlNbOfDocsField = value;
            }
        }
    }
}
